let obj={
    "Alluri Sitharama Raju":['Araku Valley',
                             'Paderu',
                            'Rampachodavaram'],
    "Annamayya":['Rajampet',
                'Kodur',
                'Rayachoti',
                'Madanapalle'],
    "Anakapalli":['Chodavaram',
                    'Madugula',
                    'Anakapalli',
                    'Pendurthi',
                    'Elamanchili',
                    'Payakaraopet',
                    'Narsipatnam'],
    "Anantapuramu":[
        'Rayadurg',
        'Uravakonda',
        'Guntakal',
        'Tadpatri',
        'Singanamala',
        'Anantapur Urban',
        'Kalyandurg',
        'Raptadu',
    ],
    "Bapatla":[
        'Vemuru  ',
        'Repalle',
        'Bapatla',
        'Parchur',
        'Addanki',
        'Chirala',
        'Santhanuthalapadu',
    ],
    "Chittoor":[
        'Punganur',
        'Nagari',
        'Gangadhara Nellore  ',
        'Chittoor',
        'Puthalapattu',
        'Palamaneru',
        'Kuppam',
    ],
    "Dr. B.R. Ambedkar Konaseema":[
        'Ramachandrapuram',
        'Mummidivaram',
        'Amalapuram  ',
        'Razole  ',
        'Gannavaram  ',
        'Kothapeta',
        'Mandapeta',

    ],
    "East Godavari":[
        'Anaparthy',
        'Rajanagaram',
        'Rajamahendravaram City',
        'Rajamahendravarm Rural',
        'kovvur  ',
        'Nidadavole',
        'Gopalapuram  ',
    ],

    "Eluru":[
        'Unguturu',
        'Denduluru',
        'Eluru',
        'Polavaram  ',
        'Chintalapudi  ',
        'Nuzvid',
        'Kaikalur',
    ],
    "Guntur":
    [
        'Tadikonda  ',
        'Managalagiri ',
        'Ponnur ',
        'Tenali',
        'Prathipadu  ',
        'Guntur West',
        'Guntur East',
    ],
    "Kakinada":[
        'Tuni',
        'Prathipadu',
        'Pithapuram',
        'Kakinada Rural',
        'Peddapuram',
        'Kakinada City',
        'Jaggampeta',
    ],

    "Krishna":[
        'Gannavaram',
        'Gudivada',
        'Pedana',
        'Machilipatnam',
        'Avanigadda',
        'Pamuru',
        'Penamaluru',
    ],

    "Kurnool":[
        'Kurnool',
        'Kodumuru',
        'Yemmiganur',
        'Mantralayam',
        'Adoni',
        'Alur',
        'Pathilkonda',

    ],
    "Nandyal":[
        'Allagadda',
        'Srisailam',
        'Nandikotkur',
        'Nandyal',
        'Banaganepalle',
        'Dhone',
        'Panyam',
    ],
    "NTR":[
        'Tiruvuru',
        'Vijayawada West',
        'Vijayawada Central',
        'Vijayawada East',
        'Mylavaram',
        'Nandigama',
        'Jaggayyapeta',
    ],
    "Palnadu":[
        'Pedakurapadu',
        'Chilakaluripet',
        'Narasaraopet',
        'Sattenapalle',
        'Vinukonda',
        'Gurajala',
        'Macherla',
    ],
       "Parvathipuram Manyam":[
        'Parvathipuram',
        'Palakonda',
        'Kurupam',
        'Salur',
    ],

    "Prakasam":[
        'Santhanuthalapadu',
        'Yerragondapalem',
        'Darsi',
        'Ongole',
        'Kondapi',
        'Markapuram',
        'Giddalur',
        'Kanigiri',
    ],
    
    "Sri Potti Sriramulu Nellore":[
        'Sarvepalli',
        'Kandukur',
        'Kavali',
        'Atmakur',
        'Kovuru',
        'Nellore City',
        'Nellore Rural',
        'Udayagiri',
    ],
    "Sri Sathya Sai":[
        'Madaksira',
        'Hindupuram',
        'Penukonda',
        'Puttaparthi',
        'Dharmavaram',
        'Kadiri',
    ],

    "Srikakulam":[
        'Ichchapuram',
        'Palasa',
        'Tekkali',
        'Pathapatnam',
        'Srikakulam',
        'Amadalavalasa',
        'Narasannapeta',
        'Etcherla'
    ],
    
    "Tirupati":[
        'Tirupati',
        'Sullurpeta',
        'Venkatagiri',
        'Guduru',
        'Srikalahasti',
        'Satyavedu',
        'Chandragiri',
    ],
    
    "Vizianagaram":[
        'Rajam',
        'Bobbili',
        'Cheepurupalli',
        'Gajapathinagaram',
        'Nellimarla',
        'Vizianagaram',
        'Srungavarapukota',
    ],
    
    "Vishakapatnam":[
        'Bheemili',
        'Visakhapatnam East',
        'Visakhapatnam West',
        'Visakhapatnam North',
        'Visakhapatnam South',
        'Gajuwaka',
        'Pendurthi ',
    ],
    

    
    "West Godavari":[
        'Achanta',
        'Palakollu',
        'Narsapuram',
        'Bhimavaram',
        'Undi',
        'Tanuku',
        'Tadepalligudem',
    ],
    
    "YSR":[
        'Badvel',
        'Jammalamadugu',
        'Kadapa',
        'Kamalapuram',
        'Mydukur',
        'Proddatur',
        'Pulivendula',
        'Rajampet',
    ],
    
}