tdp_candidates={
  "Ichchapuram": "ASHOK BENDALAM",
  "Palasa": "GOUTHU SIREESHA",
  "Tekkali": "ATCHANNAIDU KINJARAPU",
  "Pathapatnam": "MAMIDI GOVINDA RAO",
  "Srikakulam": "GONDU SHANKAR",
  "Amadalavalasa": "KOONA RAVI KUMAR",
  "Narasannapeta": "BAGGU RAMANAMURTHY",
  "Rajam": "KONDRU MURALI MOHAN",
  "Kurupam": "JAGADEESWARI THOYAKA",
  "Parvathipuram": "BONELA VIJAYA CHANDRA",
  "Salur": "GUMMIDI SANDHYARANI",
  "Bobbili": "R.V.S.K.K.RANGA RAO @ BABYNAYANA",
  "Cheepurupalle": "KALAVENKATARAO KIMIDI",
  "Gajapathinagaram": "KONDAPALLI SRINIVAS",
  "Vizianagaram": "ADITI VIJAYALAKSHMI GAJAPATHI RAJU PUSAPATI",
  "Srungavarapukota": "KOLLA LALITHA KUMARI",
  "Bhimili": "GANTA SRINIVASA RAO",
  "Visakhapatnam East": "RAMAKRISHNA BABU VELAGAPUDI",
  "Visakhapatnam West": "P.G.V.R.NAIDU(GANABABU)",
  "Gajuwaka": "PALLA SRINIVAS RAO",
  "Chodavaram": "SURYA NAGA SANYASI RAJU KALIDINDI",
  "Madugula": "BANDARU SATYANARAYANA MURTHY",
  "Payakaraopet": "ANITHA VANGALAPUDI",
  "Narsipatnam": "AYYANNAPATRUDU CHINTAKAYALA",
  "Tuni": "DIVYA YANAMALA",
  "Prathipadu": "VARUPULA SATYA PRABHA",
  "Peddapuram": "CHINA RAJAPPA NIMMAKAYALA",
  "Kakinada City": "VANAMADI VENKATESWARA RAO @ KONDABABU",
  "Ramachandrapuram": "VASAMSETTI. SUBASH",
  "Mummidivaram": "DATLA SUBBARAJU (BUCHIBABU)",
  "Amalapuram": "AITHABATHULA ANANDARAO",
  "Kothapeta": "BANDARU SATYANANDA RAO",
  "Mandapeta": "JOGESWARA RAO.V",
  "Rajahmundry City": "ADIREDDY SRINIVAS",
  "Rajahmundry Rural": "GORANTLA BUTCHAIAH CHOUDARY",
  "Jaggampeta": "JYOTHULA NEHRU",
  "Rampachodavaram": "MIRIYALA SIRISHA DEVI",
  "Kovvur": "MUPPIDI VENKATESWARA RAO",
  "Achanta": "SATYANARAYANA PITHANI",
  "Palacole": "DR.NIMMALA RAMANAIDU",
  "Undi": "KANUMURU RAGHU RAMA KRISHNA RAJU (R R R)",
  "Tanuku": "ARIMILLI RADHA KRISHNA",
  "Denduluru": "CHINTAMANENI PRABHAKAR",
  "Eluru": "RADHA KRISHNAYYA BADETI",
  "Gopalapuram": "MADDIPATI VENKATA RAJU",
  "Chintalapudi": "ROSHAN KUMAR SONGA",
  "Tiruvuru": "KOLIKAPUDI SRINIVASA RAO",
  "Nuzvid": "KOLUSU PARTHA SARATHY",
  "Gannavaram": "YARLAGADDA VENKATA RAO",
  "Gudivada": "VENIGANDLA RAMU",
  "Pedana": "KAGITHA KRISHNAPRASAD",
  "Machilipatnam": "KOLLU. RAVINDRA",
  "Pamarru": "KUMAR RAJA VARLA",
  "Penamaluru": "BODE PRASAD",
  "Vijayawada Central": "BONDA UMAMAHESWARARAO",
  "Vijayawada East": "GADDE RAMA MOHAN",
  "Mylavaram": "VASANTHA VENKATA KRISHNA PRASAD",
  "Nandigama": "TANGIRALA SOWMYA",
  "Jaggayyapeta": "RAJAGOPAL SREERAM (TATAIAH)",
  "Pedakurapadu": "BHASHYAM PRAVEEN",
  "Tadikonda": "TENALI SRAVAN KUMAR",
  "Mangalagiri": "NARA LOKESH",
  "Ponnur": "DHULIPALLA NARENDRA KUMAR",
  "Vemuru": "ANANDA BABU NAKKA",
  "Repalle": "ANAGANI SATYA PRASAD",
  "Bapatla": "VEGESANA NARENDRA VARMA RAJU",
  "Prathipadu": "BURLA RAMANJANEYULU",
  "Guntur West": "GALLA MADHAVI",
  "Guntur East": "MOHAMMED NASEER AHMED",
  "Chilakaluripet": "PRATHIPATI PULLARAO",
    "Narasaraopet": "ARAVINDA BABU CHADALAVADA",
    "Sattenapalle": "KANNA LAKSHMINARAYANA",
    "Vinukonda": "GONUGUNTLA VENKATA SIVA SITA RAMA ANZANNEYLLU",
    "Gurajala": "YARAPATHINENI SRINIVASA RAO",
    "Macherla": "JULAKANTI BRAHMANANDA REDDY",
    "Parchur": "YELURI SAMBASIVA RAO",
    "Addanki": "GOTTIPATI RAVI KUMAR",
    "Chirala": "MADDULURI MALA KONDAIAH",
    "Santhanuthalapadu": "VIJAY KUMAR B.N",
    "Ongole": "DAMACHARLA JANARDHANA RAO",
    "Kandukur": "INTURI NAGESWARA RAO",
    "Kondapi": "DOCTOR DOLA SREE BALA VEERANJANEYA SWAMY",
    "Markapuram": "KANDULA NARAYANA REDDY",
    "Giddalur": "ASHOK REDDY MUTHUMULA",
    "Kanigiri": "DR. UGRA NARASIMHA REDDY MUKKU",
    "Kavali": "DAGUMATI VENKATA KRISHNA REDDY",
    "Atmakur": "ANAM.RAMANARAYANA REDDY",
    "Kovur": "PRASHANTHI REDDY VEMIREDDY",
    "Nellore City": "NARAYANA PONGURU",
    "Nellore Rural": "KOTAMREDDY SRIDHAR REDDY",
    "Sarvepalli": "CHANDRA MOHAN REDDY SOMIREDDY",
    "Gudur": "PASIM SUNIL KUMAR",
    "Sullurpeta": "NELAVALA VIJAYASREE",
    "Venkatagiri": "KURUGONDLA RAMAKRISHNA",
    "Udayagiri": "KAKARLA SURESH",
    "Kadapa": "MADHAVI REDDAPPA GARI",
    "Rayachoti": "MANDIPALLI RAMPRASAD REDDY",
    "Kamalapuram": "KRISHNA CHAITANYA REDDY PUTHA",
    "Proddatur": "NANDYALA VARADA RAJULA REDDY",
    "Mydukur": "SUDHAKAR PUTTA",
    "Allagadda": "AKHILA PRIYA BHUMA",
    "Srisailam": "BUDDA RAJASEKHARA REDDY",
    "Nandikotkur": "G JAYASURYA",
    "Kurnool": "T.G.BHARATH",
    "Panyam": "GOWRU CHARITHA REDDY",
    "Nandyal": "NASYAM MOHAMMED FAROOK",
    "Banaganapalle": "B.C. JANARDHAN REDDY",
    "Dhone": "KOTLA JAYA SURYA PRAKASH REDDY",
    "Pattikonda": "K.E. SHYAM KUMAR",
    "Kodumur": "BOGGULA DASTAGIRI",
    "Yemmiganur": "B. JAYANAGESWARA REDDY",
    "Rayadurg": "KALAVA SRINIVASULU",
    "Uravakonda": "PAYYAVULA KESHAV",
    "Guntakal": "GUMMANUR JAYARAM",
    "Tadpatri": "ASHMIT REDDY J.C",
    "Singanamala": "BANDARU SRAVANI SREE",
    "Anantapur Urban": "DAGGUPATI PRASAD",
    "Kalyandurg": "AMILINENI SURENDRA BABU",
    "Raptadu": "PARITALA SUNITHAMMA",
    "Madakasira": "M.S.RAJU",
    "Hindupur": "NANDAMURI BALAKRISHNA",
    "Penukonda": "S. SAVITHA",
    "Puttaparthi": "PALLE SINDHURA REDDY",
    "Kadiri": "KANDIKUNTA VENKATA PRASAD",
    "Pileru": "NALLARI KISHAN KUMAR REDDY",
    "Madanapalle": "M.SHAJAHAN BASHA",
    "Chandragiri": "VENKATA MANI PRASAD PULLIVARTHI",
    "Srikalahasti": "BOJJALA VENKATA SUDHIR REDDY",
    "Satyavedu": "KONETI ADIMULAM",
    "Nagari": "GALI BHANU PRAKASH",
    "Gangadhara Nellore (SC)": "DR. VM. THOMAS",
    "Chittoor": "GURAJALA JAGAN MOHAN (GJM)",
    "Puthalapattu": "K MURALI MOHAN",
    "Palamaner": "AMARANATHA REDDY. N",
    "Kuppam": "CHANDRABABU NAIDU NARA",
    "Pulivendula":"B.Tech Ravi",
  };
  